name: pull-request

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.5.0
        with:
          fail_on_error: true
      - name: run tests
        run: ./gradlew checkstyleMain test
      - name: Push Checkstyle report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/main.xml'
